implement selectdeparser and related deparser like groupby, limit, ...
StEx2022-23/sql2regex pull request #36
Opened 2022-05-19 08:32 UTC by binkertpat

2022-05-23 16:11 UTC, Alletkla requested changes

2022-05-23 18:36 UTC, binkertpat commented on src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
> +            concat = concat.replace("\\(", "\\\\(").replace("\\)", "\\\\)");
fixed

2022-05-23 18:36 UTC, binkertpat commented on src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
> +        alternativeWritingStyles.append(str.replace("\\(", "\\\\(").replace("\\)", "\\\\)")).append('|');
fixed

2022-05-23 19:13 UTC, binkertpat commented on src/main/java/sqltoregex/settings/SettingsMapBuilder.java
> +    private final Set<ExpressionRotation> expressionRotations;
done

2022-05-23 19:14 UTC, binkertpat commented on src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
> +        if (!orderByElement.isAsc()) {
done

2022-05-23 19:14 UTC, binkertpat commented on src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
> +    private final boolean isKeywordSpellingMistake;
done

2022-05-23 19:14 UTC, binkertpat commented on src/main/java/sqltoregex/deparser/GroupByDeParserForRegEx.java
> +    private final boolean isKeywordSpellingMistake;
done

2022-05-23 19:15 UTC, binkertpat commented on src/test/java/sqltoregex/deparser/LimitDeParserForRegExTest.java
> +        Matcher matcher = pattern.matcher(toChecked);
done

2022-05-24 21:24 UTC, Alletkla requested changes

2022-05-24 21:24 UTC, Alletkla commented on src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
> +            buffer.append("WITH ");
require whitespace instead of normal whitespace character

2022-05-24 21:42 UTC, Alletkla approved these changes

2022-05-24 21:43 UTC, merged